name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if update available
        id: run
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: library/alpine:latest
          image: ${{ secrets.DOCKER_USERNAME }}/shadowsocks-libev:alpine
        continue-on-error: true
        if: github.event_name == 'schedule'
      - name: Check on result
        id: check
        run: |
          if [[ ${{ steps.run.outcome }} == 'success' ]]; then
            echo "needs-updating=${{ steps.run.outputs.needs-updating }}" >> $GITHUB_OUTPUT
          else
            echo "needs-updating=true" >> $GITHUB_OUTPUT
          fi
        if: github.event_name == 'schedule'

  build:
    needs: check
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'schedule' ||
      needs.check.outputs.needs-updating == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}

      - name: check and set image version
        id: prepare
        run: |
          REPOSITORY=${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME=shadowsocks-libev
          TAGS="${REPOSITORY}/${IMAGE_NAME}:alpine,${REPOSITORY}/${IMAGE_NAME}:latest"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prepare.outputs.tags }}

  keepalive:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
